# -*- coding: utf-8 -*-
"""Uber_Requested_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15S89lf1_nW8OlxwJ4yVExOTSY7TCJdJT
"""

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

from google.colab import files

uploaded=files.upload()

uploaded

#Loading Uber dataset
uber=pd.read_csv('Uber.csv')

#Looking first five data of uber
uber.head()

#Looking number of Rows and Columns
uber.shape

#Convert Request-timestamp to uniform datetime format
uber["Request timestamp"] = uber["Request timestamp"].apply(lambda x : pd.to_datetime(x))
uber.head()

#convert Drop-timestamp to uniform datetime format
uber["Drop timestamp"]=uber['Drop timestamp'].apply(lambda x: pd.to_datetime(x))
uber.head()

#Total request in City and Airport
uber['Pickup point'].value_counts()

#Bar-Graph of total request in City and Airport
plt.figure(figsize=(8,8))
plt.bar(list(uber['Pickup point'].value_counts().keys()),list(uber['Pickup point'].value_counts()),color=["r","b",])
plt.title('Total request in City and Airport')
plt.xlabel('Location')
plt.ylabel('total Data')
plt.show()

#Looking at the status request
uber['Status'].value_counts()

#Bar- Graph of the Total request
plt.figure(figsize=(8,8))
plt.bar(list(uber['Status'].value_counts().keys()),list(uber['Status'].value_counts()),color=["r","b",'purple'])
plt.title('Total request of the Data')
plt.xlabel('Status')
plt.ylabel('total Data')
plt.show()

#Total number of data by per category
plt.figure(figsize=(10,6))
sns.countplot(x="Pickup point",hue="Status",data=uber)
plt.show()

#filter all the cancelled trip
cancelled_trip=uber[uber['Status']=='Cancelled']

cancelled_trip.head()

print(cancelled_trip.shape)

#looking for the data where cars is not available
no_cars=uber[uber['Status']=='No Cars Available']

no_cars.head()

print(no_cars.shape)

completed_trip=uber[uber['Status']=='Trip Completed']

completed_trip.head()

print(completed_trip.shape)

#making Pie-chart of the data
statuslabels = ["Cancelled", "No Cars Available", "Trip Completed"]
x=np.array([1264,2650,2831])
plt.pie(x,labels = statuslabels, autopct = '%2.2f%%',shadow=True,startangle=90)
plt.style.use('ggplot')
plt.title('Uber Requested Data')
plt.axis('equal')
plt.legend(loc='bottom left')

#Pie plot of the Pickup point Data
#making Pie-chart of the data
statuslabels = ["City", "Airport"]
x=np.array([3507,3238,])
plt.pie(x,labels = statuslabels, autopct = '%2.2f%%',shadow=True,startangle=180)
plt.style.use('ggplot')
plt.title('Pickup Point')
plt.axis('equal')
plt.legend(loc='bottom left')

